---
title: "Assignment 4"
author: "Kelly Primrose and Diana Schoder"
format: html
editor: visual
warning: false
---

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(sf)
library(tigris)
```

## Graph One

[Capital Bikeshare data](https://capitalbikeshare.com/system-data) shows that both casual users and members began their trips throughout the Capital Bikeshare system in January 2023, including in DC, Maryland, and Virginia.

```{r}

#Read in Capital Bikeshare data
cabi <- read.csv(file = '202301-capitalbikeshare-tripdata.csv')

start_station <- st_as_sf(cabi, coords = c("start_lng", "start_lat")) %>% 
st_set_crs(value = 4326)

dc <- states(progress_bar = FALSE) %>%
 filter(STUSPS == "DC") 

md <- counties("MD", progress_bar = FALSE) %>%
  filter(COUNTYFP == "031" | COUNTYFP == "033") 

va <- counties("VA", progress_bar = FALSE) %>%
  filter(COUNTYFP == "013" |COUNTYFP == "059" | COUNTYFP == "510")  

ggplot() +
  geom_sf(data = dc) +
   geom_sf(data = md) +
   geom_sf(data = va) +
  geom_sf(data = start_station,
          aes(color = member_casual)) +
   labs(title = "Member and Casual Trips in January 2023", subtitle = "Capital Bikeshare Starting Stations", caption = "Data Source: Capital Bikeshare", fill = "User Types") +
  theme_void()



```



## Graph Two

```{r}
# Put end time variable into date format and extract day of the week
end_time <- ymd_hms(cabi$ended_at)
day <- wday(end_time)

# Graph Total Bikeshare Trips by Day of the Week
cabi %>% 
   ggplot() +
   geom_bar(mapping = aes(x = day)) +
   labs(title = "Total Bikeshare Trips by Day of the Week", subtitle = "Capital Bikeshare, January 2023", caption = "Data Source: Capital Bikeshare") +
   xlab("Day of the Week") +
   ylab("Total Bikeshare Trips") +
  theme_void()

```

## Graph Three

## Graph Four

